coffehouse/about/urls.py
from django.conf.urls import url
from . import views

app_name = 'about'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^find-us', views.find_us, name='find_us'),
]

coffehouse/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home_page),
]

coffehouse/menu/urls.py
from django.conf.urls import url
from . import views

app_name = 'menu'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

coffehouse/orders/urls.py
from django.conf.urls import url

from . import views

app_name = 'orders'
urlpatterns = [
    url(r'^unprocessed', views.unprocessed_orders, name='unprocessed'),
    url(r'^proceed', views.proceed_order, name='proceed_order'),
    url(r'^show_chart', views.show_chart, name='show_chart'),
    url(r'^orders_history', views.orders_history, name='orders_history'),
    url(r'^cancel_order', views.cancel_order, name='cancel_order'),
]

coffehouse/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.views.generic import TemplateView

from coffehouse.users import views


urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),

    # url(r'^$', TemplateView.as_view(template_name='homepage.html'), name="homepage"),
    url(r'^', include('coffehouse.home.urls', namespace="home")),

    # url(r'^about/', about_views.contact),
    url(r'^about/', include('coffehouse.about.urls', namespace='about')),
    url(r'^drinks/(?P<drink_name>\D+)/', TemplateView.as_view(template_name='drinks/menu.html')),

    # url(r'^stores/', stores_views.detail, {'location': 'Headquarters'}),
    # url(r'^stores/(?P<store_id>\d+)/', stores_views.detail),
    url(r'^stores/', include('coffehouse.stores.urls'), name='stores'),
    url(r'^orders/', include('coffehouse.orders.urls'), name='orders'),

    url(r'^users/', include('coffehouse.users.urls', namespace="users"), name='users'),
    url(r'^menu/', include('coffehouse.menu.urls'), name='menu'),

    url(r'^ajax/validate_username/', views.validate_username, name='validate_username'),

]

coffehouse/menu/models.py
from django.db import models

# Create your models here.

coffehouse/orders/models.py
from django.db import models

from coffehouse.users.models import Customer, Service


class Food(models.Model):
    name = models.CharField(max_length=50)
    number_in_menu = models.IntegerField(default=-1)
    price = models.DecimalField(max_length=4, max_digits=6, decimal_places=2)
    # quantity = models.IntegerField()
    week_day = models.IntegerField(default=-1)
    img_url = models.CharField(max_length=1000, default=" ")
    description = models.CharField(max_length=1000, default="")
    note = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name


class Drink(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_length=4, max_digits=6, decimal_places=2)
    description = models.CharField(max_length=1000, default="")
    note = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(Customer, related_name='client', on_delete=models.CASCADE, null=True)
    food = models.ManyToManyField(Food, related_name='foods')
    drink = models.ManyToManyField(Drink, related_name='drinks', default=None)
    created_at = models.DateField(auto_now_add=True)
    processed = models.BooleanField(default=False)
    processed_by = models.ForeignKey(Service, related_name='processed_by', on_delete=models.CASCADE, null=True)
    note = models.CharField(max_length=255, null=True)
    total_price = models.DecimalField(default=0.0, max_length=4, max_digits=6, decimal_places=2)

    def __str__(self):
        return "{user_name} ordered something at: {date}".format(user_name=self.user.__str__(),
                                                                 date=self.created_at.__str__())


class Chart(models.Model):
    user = models.OneToOneField(Customer, related_name='customer', on_delete=models.CASCADE, null=True)
    food = models.ManyToManyField(Food, related_name='food_in_chart', default=None)
    drink = models.ManyToManyField(Drink, related_name='drinks_in_chart', default=None)
    total_price = models.DecimalField(default=0.0, max_length=4, max_digits=6, decimal_places=2)

    def __str__(self):
        return "{username}' shopping chart".format(username=self.user.__str__())

coffehouse/stores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

coffehouse/menu/forms.py
from django import forms
from ..orders.models import Order, Drink


class AddToChart(forms.ModelForm):
    # DRINK_LIST = Drink.objects.all()
    # food_name = forms.CharField(widget=forms.TextInput())
    menu_number = forms.ChoiceField(choices=[(x, x) for x in range(1, 6)])
    # quantity = forms.DecimalField(widget=forms.NumberInput())
    note = forms.CharField(widget=forms.Textarea(), max_length=400, required=False)
    drink = forms.ModelChoiceField(queryset=Drink.objects.all())

    class Meta:
        model = Order
        fields = ['menu_number', 'drink', 'note']

coffehouse/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction

from coffehouse.users.models import BaseUser, Customer, Service


# class RegisterUser(forms.ModelForm):
#     login = forms.CharField(widget=forms.TextInput(), max_length=30, required=True)
#     real_name = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
#     password = forms.CharField(widget=forms.PasswordInput())
#     email = forms.EmailField(required=True)
#     address = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
#     country = forms.CharField(widget=forms.TextInput(), max_length=40, required=True)
#
#     class Meta:
#         model = CustomUser
#         fields = ['login', 'real_name', 'password', 'email', 'address', 'country']


class LoginUser(forms.Form):
    login = forms.CharField(widget=forms.TextInput(), max_length=30)
    password = forms.CharField(widget=forms.PasswordInput())


# Not in use ##########################################################################################################
class RegisterNewCustomerForm(UserCreationForm):
    address = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
    country = forms.CharField(widget=forms.TextInput(), max_length=20, required=True)

    class Meta(UserCreationForm.Meta):
        model = BaseUser
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'country']
        help_texts = {
            'username': ''
        }

        @transaction.atomic
        def save(self):
            user = super().save(commit=False)
            user.save()
            Customer.objects.create(user=user)
            return user


class CustomerChangeForm(UserChangeForm):
    class Meta:
        model = Customer
        fields = UserChangeForm.Meta.fields


class RegisterNewServiceForm(UserCreationForm):
    address = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
    country = forms.CharField(widget=forms.TextInput(), max_length=20, required=True)
    IBAN = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)

    class Meta:
        model = BaseUser
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'country', 'IBAN']

        @transaction.atomic
        def save(self):
            user = super().save(commit=False)
            user.save()
            Service.objects.create(user=user)
            return user


class UserProfileChange(UserChangeForm):
    address = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
    country = forms.CharField(widget=forms.TextInput(), max_length=20, required=True)

    class Meta:
        model = BaseUser
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'country']
        help_texts = {
            'username': None
        }

coffehouse/about/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponsePermanentRedirect
from django.urls import reverse

from coffehouse.users.key.key import Key


def index(request):
    redirect_home = HttpResponsePermanentRedirect(reverse('homepage'))

    return render(request, 'about/index.html', {'homepage': redirect_home})


def contact(request):
    return render(request, 'about/contact.html')


def find_us(request):
    key = Key().get_key()
    return render(request, 'about/find_us.html', {'key': key})

coffehouse/home/views.py
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import render
from django.urls import reverse


def home_page(request):
    # redirect_stores = HttpResponsePermanentRedirect(reverse('stores'))
    #
    # render_in_template = {'stores': redirect_stores}
    return render(request, 'homepage.html')

coffehouse/menu/views.py
from django.shortcuts import render

from coffehouse.users.models import Customer
from ..orders.models import Food, Chart, Drink
from .forms import AddToChart


# def index(request):
#     if request.method == 'POST':
#         new_order = NewOrder(request.POST)
#         if new_order.is_valid():
#             user = request.user
#             customer = Customer.objects.get(user=user)
#             menu_number = new_order.cleaned_data.get('menu_number')
#             note = new_order.cleaned_data.get('note')
#             # quantity = new_order.cleaned_data.get('quantity')
#
#             food = Food.objects.get(number_in_menu=menu_number)
#
#             order = new_order.save(commit=False)
#             order.food = food
#             order.user = customer
#             order.note = note
#             order.save()
#
#             return render(request, 'orders/successful_order.html')
#         else:
#             return render(request, 'orders/error_order.html')
#     else:
#         all_food = Food.objects.all()
#         form = NewOrder()
#
#     return render(request, 'menu/menu.html', {'form': form, 'all_food': all_food})

def index(request):
    all_food = Food.objects.all()
    form = AddToChart()

    if request.method == 'POST':
        new_order = AddToChart(request.POST)
        if new_order.is_valid():
            user = request.user
            customer = Customer.objects.get(user=user)
            chart = Chart.objects.get(user=customer)

            menu_number = new_order.cleaned_data.get('menu_number')
            drink_name = new_order.cleaned_data.get('drink', None)

            food = Food.objects.get(number_in_menu=menu_number)

            if drink_name is not None:
                try:
                    drink = Drink.objects.get(name=drink_name)
                    chart.drink.add(drink)
                    chart.total_price += drink.price
                except:
                    pass

            chart.food.add(food)
            chart.total_price += food.price

            chart.save()

            return render(request, 'menu/menu.html', {'form': form, 'all_food': all_food})
        else:
            return render(request, 'orders/error_order.html')
    else:
        return render(request, 'menu/menu.html', {'form': form, 'all_food': all_food})

coffehouse/orders/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect

from coffehouse.orders.models import Order, Chart, Food, Drink
from coffehouse.users.models import Service, Customer, BaseUser


def successful_order(request):
    return render(request, 'orders/successful_order.html')


def unsuccessful_order(request):
    return render(request, 'orders/error_order.html')


@login_required
def unprocessed_orders(request):
    if request.user.is_service:
        service = request.user
        orders = Order.objects.filter(processed=False)

        return render(request, 'orders/unprocessed_orders.html', {'orders': orders})

    return redirect('users:login')


def proceed_order(request):
    order_id = request.GET.get('order_id', None)
    success = False
    try:
        order = Order.objects.get(id=order_id)
        service = Service.objects.get(user=request.user)
        order.processed_by = service
        order.processed = True

        order.save()

        success = True
    except:
        success = False

    data = {
        'message': success
    }

    return JsonResponse(data)


@login_required
def cancel_order(request):
    order_id = request.GET.get('order_id', None)
    success = False
    try:
        order = Order.objects.get(id=order_id)
        order.delete()
        success = True
    except:
        success = False

    data = {
        'message': success
    }

    return JsonResponse(data)


@login_required
def show_chart(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    chart = Chart.objects.get(user=customer)

    food = chart.food.all()
    drinks = chart.drink.all()

    if request.GET.get('order'):
        new_order = Order()
        new_order.user = customer
        new_order.save()

        food_list = list(chart.food.all())
        for food in food_list:
            db_food = Food.objects.get(name=food.name)
            new_order.food.add(db_food)

        drink_list = list(chart.drink.all())
        for drink in drink_list:
            db_drink = Drink.objects.get(name=drink.name)
            new_order.drink.add(db_drink)

        new_order.total_price = chart.total_price
        new_order.save()

        chart.food.clear()
        chart.drink.clear()
        chart.total_price = 0.0
        chart.save()

        return render(request, 'orders/successful_order.html')

    return render(request, 'orders/show_chart.html', {'food': food, 'drinks': drinks, 'total_price': chart.total_price})


@login_required(login_url='/users/login')
def orders_history(request):
    user = request.user
    customer = Customer.objects.get(user=user)

    customer_orders = Order.objects.filter(user=customer)

    return render(request, 'orders/orders_history.html', {'orders': customer_orders})

coffehouse/stores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


# Create your views here.

# When function parameter has default value this parameter is optional
def detail(request, store_id='1', location=None):

    # Example of accessing query parameters
    # This is example of GET HTTP request. When POST request is the same just
    # GET changes to POST
    hours = request.GET.get('hours', None)
    map = request.GET.get('map', None)

    return render(request, 'stores/detail.html')


def index(request):
    return render(request, 'stores/index.html')

coffehouse/users/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout

from coffehouse.users.forms import RegisterNewCustomerForm, LoginUser
from coffehouse.users.models import BaseUser, Customer


def show_profile(request):
    user = request.user
    customer = Customer.objects.get(user=user)

    return render(request, 'users/profile.html', {'base_user': user,'customer': customer})


def test_register(request):
    if request.method == 'POST':
        new_customer = RegisterNewCustomerForm(request.POST)
        if new_customer.is_valid():
            new_customer.save(commit=False)

            return render(request, 'users/welcome_new_user.html')
        else:
            reasons = new_customer.error_messages.items()
            return render(request, 'users/register_error.html', {'reasons': reasons})
    else:
        form = RegisterNewCustomerForm()

    return render(request, 'users/test_register.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        visitor = LoginUser(request.POST)
        if visitor.is_valid():
            username = visitor.cleaned_data['login']
            password = visitor.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)

                return render(request, 'homepage.html')
            else:
                error = ValueError("Bad credentials!")

                return render(request, 'some_error.html', {'reasons': error.args})

    form = LoginUser

    return render(request, 'users/login.html', {'form': form})


def logout_user(request):
    logout(request)

    return render(request, 'homepage.html')


def welcome(request):
    return render(request, 'users/welcome_new_user.html')


def creation_service_success(request):
    return render(request, 'users/welcome_new_user.html')


def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': BaseUser.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)


# def register(request):
#     if request.method == 'POST':
#         new_user = RegisterUser(request.POST)
#         if new_user.is_valid():
#             new_user.save()
#
#             return render(request, 'users/welcome_new_user.html')
#         else:
#             return render(request, 'users/register_error.html')
#     else:
#         form = RegisterUser()
#
#     return render(request, 'users/register.html', {'form': form})

coffehouse/templates/orders/error_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error order</title>
</head>
<body>
    <p>
        Something went wrong
    </p>
</body>
</html>

coffehouse/templates/orders/orders_history.html
{% extends 'base.html' %}

{% block title %} History of orders {% endblock %}

{% block extra_head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/orders/orders_history_style.css" %}">
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <H1>Orders history</H1>
        {% for order in orders %}
            <div class="old_order">
                <div class="success_delete" style="display: none;">
                    <p> This order was successfully canceled! </p>
                </div>
                <div class="error" style="display: none;">
                    <p> Some error while canceling order. Try later! </p>
                </div>

                <h3>Food:</h3>
                {% for food in order.food.all %}
                    {{ food.name }}
                    <br>
                {% endfor %}
                {% if order.drink.all.count > 0 %}
                    <br>
                    <h3>Drinks</h3>
                    {% for drink in order.drink.all %}
                        {{ drink.name }}
                    {% endfor %}
                {% endif %}

                <br>
                {% if order.processed %}
                    <p>Status: PROCESSED </p>
                {% else %}
                    <p>Status: WAITING FOR PROCESSING </p>
                    <input type="submit" class="btn-link" name="proceed" value="CANCEL order"
                           onclick="cancelOrder(this, {{ order.pk }});">
                {% endif %}
                <div class="price"> {{ order.total_price }} $</div>

            </div>
        {% endfor %}

    </div>
{% endblock content %}

{% block extra_scripts %}
    <script>
        var cancelOrder = function (button, orderPK) {
            console.log("Order number: " + orderPK);
            $.ajax({
                url: '{% url "orders:cancel_order" %}',
                data: {
                    'order_id': orderPK
                },
                dataType: 'json',
                success: function (data) {
                    if (data.message) {
                        $(button).siblings(".success_delete").show();
                        $(button).hide();
                    } else {
                        $(button).siblings(".error").show();
                    }
                }
            })
        };
    </script>
{% endblock extra_scripts %}

coffehouse/templates/orders/show_chart.html
{% extends 'base.html' %}

{% block title %} Your chart {% endblock %}

{% block extra_head %} 
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/orders/show_chart_style.css" %}">
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <h1> Your shopping chart: </h1>

        <h2>Food</h2>
        {% for item in food %}
            <div class="chart_item">
                <p> {{ item.name }}</p>
                <p> Price: {{ item.price }}$</p>
            </div>
        {% endfor %}

        <h2> Drinks: </h2>
        {% for item in drinks %}
            <div class="chart_item">
                <p> {{ item.name }}</p>
                <p> Price: {{ item.price }}$</p>
            </div>
        {% endfor %}
    ===============================================================

    <p>Total price is: {{ total_price }}</p>

    {% if total_price > 0 %}
        <form method="get">
            <input type="submit" value="ORDER" name="order"/>
        </form>
    {% endif %}
    </div>


{% endblock content%}

{% block extra_scripts %}
{% endblock extra_scripts %}

coffehouse/templates/orders/successful_order.html
{% extends 'base.html' %}
{% load static %}
{% block extra_head %}
{#    link here custom .css file#}
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <h1> Your order was successful! </h1>
        <img src="{% static "images/done_sign.png"%}">
        <br>
        <a href="{% url 'orders:orders_history' %}">Go to history of your orders</a>
    </div>
{% endblock content%}

coffehouse/templates/orders/unprocessed_orders.html
{% extends 'base.html' %}

{% block title %} Unprocessed orders! {% endblock %}

{% block extra_head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/orders/unprocessed_orders_style.css" %}">
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <h1> Orders waiting to be processed: </h1>

        {% for order in orders %}
            <div class="order">
                <div class="success_processed" style="display: none;">
                    <p> This order was successfully processed! </p>
                </div>
                <div class="error" style="display: none;">
                    <p> Some error while processing order. Try later! </p>
                </div>
                {#                not hidden stuff #}
                {% if order.food.count > 0 %}
                    Food:
                    {% for food in order.food.all %}
                        <p> {{ food }}</p>
                    {% endfor %}
                    --------------------------------- <br> <br>
                {% endif %}

                {% if order.drink.count > 0 %}
                    Drink:
                    {% for drink in order.drink.all %}
                        <p> {{ drink }}</p>
                    {% endfor %}
                {% endif %}
                <div class="line"></div>
                <p class="username"> NAME -> {{ order.user.user.username }}</p>
                <p ><b> ADDRESS -> </b> {{ order.user.address }} </p>
                <p><b> Total price -> {{ order.total_price }} $</b></p>
                <input type="submit" class="btn-link" name="proceed" value="Process order"
                       onclick="proceedOrder(this, {{ order.pk }});">
            </div>
        {% endfor %}

    </div>
{% endblock content %}

{% block extra_scripts %}
    <script>
        var proceedOrder = function (button, orderPK) {
            console.log("Order number: " + orderPK);
            $.ajax({
                url: '{% url "orders:proceed_order" %}',
                data: {
                    'order_id': orderPK
                },
                dataType: 'json',
                success: function (data) {
                    if (data.message) {
                        $(button).siblings(".success_processed").show();
                        $(button).hide();
                    } else {
                        $(button).siblings(".error").show();
                    }
                }
            })
        };
    </script>
{% endblock %}