coffehouse/about/urls.py
from django.conf.urls import url
from . import views

app_name = 'about'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^find-us', views.find_us, name='find_us'),
]

coffehouse/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home_page),
]

coffehouse/menu/urls.py
from django.conf.urls import url
from . import views

app_name = 'menu'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

coffehouse/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.views.generic import TemplateView

from coffehouse.users import views


urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),

    # url(r'^$', TemplateView.as_view(template_name='homepage.html'), name="homepage"),
    url(r'^', include('coffehouse.home.urls', namespace="home")),

    # url(r'^about/', about_views.contact),
    url(r'^about/', include('coffehouse.about.urls', namespace='about')),
    url(r'^drinks/(?P<drink_name>\D+)/', TemplateView.as_view(template_name='drinks/menu.html')),

    # url(r'^stores/', stores_views.detail, {'location': 'Headquarters'}),
    # url(r'^stores/(?P<store_id>\d+)/', stores_views.detail),
    url(r'^stores/', include('coffehouse.stores.urls'), name='stores'),
    url(r'^orders/', include('coffehouse.orders.urls'), name='orders'),

    url(r'^users/', include('coffehouse.users.urls', namespace="users"), name='users'),
    url(r'^menu/', include('coffehouse.menu.urls'), name='menu'),

    url(r'^ajax/validate_username/', views.validate_username, name='validate_username'),

]

coffehouse/users/urls.py
from django.conf.urls import url

from . import views
from . import users

app_name = 'users'
urlpatterns = [
    url(r'^$', views.show_profile, name='index'),
    # url(r'^register', views.register, name='register'),
    url(r'^login', views.login_user, name='login'),
    url(r'^logout', views.logout_user, name='logout'),
    url(r'^test/', users.RegisterNewCustomerView.as_view(), name='test_register'),
    url(r'^service-register/', users.RegisterNewServiceView.as_view(), name='register_service'),
    url(r'^welcome', views.welcome, name='welcome'),
    url(r'^profile', views.show_profile, name='show_profile'),
    url(r'^change-profile', users.CustomerProfileChangeView.as_view(), name='change_profile'),
    # url(r'^welcome', views.welcome, name='welcome')
]

coffehouse/menu/models.py
from django.db import models

# Create your models here.

coffehouse/stores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

coffehouse/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# class CustomUser(models.Model):
#     # class CustomUser(AbstractUser):
#     login = models.CharField(max_length=30)
#     real_name = models.CharField(max_length=100)
#     password = models.CharField(max_length=200)
#     email = models.EmailField()
#     address = models.CharField(max_length=100, default=" ")
#     country = models.CharField(max_length=40, default=" ")
#
#     def __str__(self):
#         return self.login


class BaseUser(AbstractUser):
    is_owner = models.BooleanField(default=False)
    is_service = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class Customer(models.Model):
    user = models.OneToOneField(BaseUser, on_delete=models.CASCADE, primary_key=True)
    address = models.CharField(max_length=100)
    country = models.CharField(max_length=40, default=" ")

    def __str__(self):
        return self.user.username


class Service(models.Model):
    user = models.OneToOneField(BaseUser, on_delete=models.CASCADE, primary_key=True)
    address = models.CharField(max_length=100, default=" ")
    country = models.CharField(max_length=40, default=" ")
    start_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(blank=True, null=True)
    IBAN = models.CharField(max_length=100, default=" ")

    def __str__(self):
        return self.user.username

coffehouse/menu/forms.py
from django import forms
from ..orders.models import Order, Drink


class AddToChart(forms.ModelForm):
    # DRINK_LIST = Drink.objects.all()
    # food_name = forms.CharField(widget=forms.TextInput())
    menu_number = forms.ChoiceField(choices=[(x, x) for x in range(1, 6)])
    # quantity = forms.DecimalField(widget=forms.NumberInput())
    note = forms.CharField(widget=forms.Textarea(), max_length=400, required=False)
    drink = forms.ModelChoiceField(queryset=Drink.objects.all())

    class Meta:
        model = Order
        fields = ['menu_number', 'drink', 'note']

coffehouse/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction

from coffehouse.users.models import BaseUser, Customer, Service


# class RegisterUser(forms.ModelForm):
#     login = forms.CharField(widget=forms.TextInput(), max_length=30, required=True)
#     real_name = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
#     password = forms.CharField(widget=forms.PasswordInput())
#     email = forms.EmailField(required=True)
#     address = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
#     country = forms.CharField(widget=forms.TextInput(), max_length=40, required=True)
#
#     class Meta:
#         model = CustomUser
#         fields = ['login', 'real_name', 'password', 'email', 'address', 'country']


class LoginUser(forms.Form):
    login = forms.CharField(widget=forms.TextInput(), max_length=30)
    password = forms.CharField(widget=forms.PasswordInput())


# Not in use ##########################################################################################################
class RegisterNewCustomerForm(UserCreationForm):
    address = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
    country = forms.CharField(widget=forms.TextInput(), max_length=20, required=True)

    class Meta(UserCreationForm.Meta):
        model = BaseUser
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'country']
        help_texts = {
            'username': ''
        }

        @transaction.atomic
        def save(self):
            user = super().save(commit=False)
            user.save()
            Customer.objects.create(user=user)
            return user


class CustomerChangeForm(UserChangeForm):
    class Meta:
        model = Customer
        fields = UserChangeForm.Meta.fields


class RegisterNewServiceForm(UserCreationForm):
    address = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
    country = forms.CharField(widget=forms.TextInput(), max_length=20, required=True)
    IBAN = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)

    class Meta:
        model = BaseUser
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'country', 'IBAN']

        @transaction.atomic
        def save(self):
            user = super().save(commit=False)
            user.save()
            Service.objects.create(user=user)
            return user


class UserProfileChange(UserChangeForm):
    address = forms.CharField(widget=forms.TextInput(), max_length=100, required=True)
    country = forms.CharField(widget=forms.TextInput(), max_length=20, required=True)

    class Meta:
        model = BaseUser
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'country']
        help_texts = {
            'username': None
        }

coffehouse/about/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponsePermanentRedirect
from django.urls import reverse

from coffehouse.users.key.key import Key


def index(request):
    redirect_home = HttpResponsePermanentRedirect(reverse('homepage'))

    return render(request, 'about/index.html', {'homepage': redirect_home})


def contact(request):
    return render(request, 'about/contact.html')


def find_us(request):
    key = Key().get_key()
    return render(request, 'about/find_us.html', {'key': key})

coffehouse/home/views.py
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import render
from django.urls import reverse


def home_page(request):
    # redirect_stores = HttpResponsePermanentRedirect(reverse('stores'))
    #
    # render_in_template = {'stores': redirect_stores}
    return render(request, 'homepage.html')

coffehouse/menu/views.py
from django.shortcuts import render

from coffehouse.users.models import Customer
from ..orders.models import Food, Chart, Drink
from .forms import AddToChart


# def index(request):
#     if request.method == 'POST':
#         new_order = NewOrder(request.POST)
#         if new_order.is_valid():
#             user = request.user
#             customer = Customer.objects.get(user=user)
#             menu_number = new_order.cleaned_data.get('menu_number')
#             note = new_order.cleaned_data.get('note')
#             # quantity = new_order.cleaned_data.get('quantity')
#
#             food = Food.objects.get(number_in_menu=menu_number)
#
#             order = new_order.save(commit=False)
#             order.food = food
#             order.user = customer
#             order.note = note
#             order.save()
#
#             return render(request, 'orders/successful_order.html')
#         else:
#             return render(request, 'orders/error_order.html')
#     else:
#         all_food = Food.objects.all()
#         form = NewOrder()
#
#     return render(request, 'menu/menu.html', {'form': form, 'all_food': all_food})

def index(request):
    all_food = Food.objects.all()
    form = AddToChart()

    if request.method == 'POST':
        new_order = AddToChart(request.POST)
        if new_order.is_valid():
            user = request.user
            customer = Customer.objects.get(user=user)
            chart = Chart.objects.get(user=customer)

            menu_number = new_order.cleaned_data.get('menu_number')
            drink_name = new_order.cleaned_data.get('drink', None)

            food = Food.objects.get(number_in_menu=menu_number)

            if drink_name is not None:
                try:
                    drink = Drink.objects.get(name=drink_name)
                    chart.drink.add(drink)
                    chart.total_price += drink.price
                except:
                    pass

            chart.food.add(food)
            chart.total_price += food.price

            chart.save()

            return render(request, 'menu/menu.html', {'form': form, 'all_food': all_food})
        else:
            return render(request, 'orders/error_order.html')
    else:
        return render(request, 'menu/menu.html', {'form': form, 'all_food': all_food})

coffehouse/orders/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect

from coffehouse.orders.models import Order, Chart, Food, Drink
from coffehouse.users.models import Service, Customer, BaseUser


def successful_order(request):
    return render(request, 'orders/successful_order.html')


def unsuccessful_order(request):
    return render(request, 'orders/error_order.html')


@login_required
def unprocessed_orders(request):
    if request.user.is_service:
        service = request.user
        orders = Order.objects.filter(processed=False)

        return render(request, 'orders/unprocessed_orders.html', {'orders': orders})

    return redirect('users:login')


def proceed_order(request):
    order_id = request.GET.get('order_id', None)
    success = False
    try:
        order = Order.objects.get(id=order_id)
        service = Service.objects.get(user=request.user)
        order.processed_by = service
        order.processed = True

        order.save()

        success = True
    except:
        success = False

    data = {
        'message': success
    }

    return JsonResponse(data)


@login_required
def cancel_order(request):
    order_id = request.GET.get('order_id', None)
    success = False
    try:
        order = Order.objects.get(id=order_id)
        order.delete()
        success = True
    except:
        success = False

    data = {
        'message': success
    }

    return JsonResponse(data)


@login_required
def show_chart(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    chart = Chart.objects.get(user=customer)

    food = chart.food.all()
    drinks = chart.drink.all()

    if request.GET.get('order'):
        new_order = Order()
        new_order.user = customer
        new_order.save()

        food_list = list(chart.food.all())
        for food in food_list:
            db_food = Food.objects.get(name=food.name)
            new_order.food.add(db_food)

        drink_list = list(chart.drink.all())
        for drink in drink_list:
            db_drink = Drink.objects.get(name=drink.name)
            new_order.drink.add(db_drink)

        new_order.total_price = chart.total_price
        new_order.save()

        chart.food.clear()
        chart.drink.clear()
        chart.total_price = 0.0
        chart.save()

        return render(request, 'orders/successful_order.html')

    return render(request, 'orders/show_chart.html', {'food': food, 'drinks': drinks, 'total_price': chart.total_price})


@login_required(login_url='/users/login')
def orders_history(request):
    user = request.user
    customer = Customer.objects.get(user=user)

    customer_orders = Order.objects.filter(user=customer)

    return render(request, 'orders/orders_history.html', {'orders': customer_orders})

coffehouse/stores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


# Create your views here.

# When function parameter has default value this parameter is optional
def detail(request, store_id='1', location=None):

    # Example of accessing query parameters
    # This is example of GET HTTP request. When POST request is the same just
    # GET changes to POST
    hours = request.GET.get('hours', None)
    map = request.GET.get('map', None)

    return render(request, 'stores/detail.html')


def index(request):
    return render(request, 'stores/index.html')

coffehouse/users/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout

from coffehouse.users.forms import RegisterNewCustomerForm, LoginUser
from coffehouse.users.models import BaseUser, Customer


def show_profile(request):
    user = request.user
    customer = Customer.objects.get(user=user)

    return render(request, 'users/profile.html', {'base_user': user,'customer': customer})


def test_register(request):
    if request.method == 'POST':
        new_customer = RegisterNewCustomerForm(request.POST)
        if new_customer.is_valid():
            new_customer.save(commit=False)

            return render(request, 'users/welcome_new_user.html')
        else:
            reasons = new_customer.error_messages.items()
            return render(request, 'users/register_error.html', {'reasons': reasons})
    else:
        form = RegisterNewCustomerForm()

    return render(request, 'users/test_register.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        visitor = LoginUser(request.POST)
        if visitor.is_valid():
            username = visitor.cleaned_data['login']
            password = visitor.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)

                return render(request, 'homepage.html')
            else:
                error = ValueError("Bad credentials!")

                return render(request, 'some_error.html', {'reasons': error.args})

    form = LoginUser

    return render(request, 'users/login.html', {'form': form})


def logout_user(request):
    logout(request)

    return render(request, 'homepage.html')


def welcome(request):
    return render(request, 'users/welcome_new_user.html')


def creation_service_success(request):
    return render(request, 'users/welcome_new_user.html')


def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': BaseUser.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)


# def register(request):
#     if request.method == 'POST':
#         new_user = RegisterUser(request.POST)
#         if new_user.is_valid():
#             new_user.save()
#
#             return render(request, 'users/welcome_new_user.html')
#         else:
#             return render(request, 'users/register_error.html')
#     else:
#         form = RegisterUser()
#
#     return render(request, 'users/register.html', {'form': form})

coffehouse/templates/users/change_profile.html
{% extends 'base.html' %}

{% block title %} Hi, {{ user.username }} {% endblock %}

{% block extra_head %} 
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/users/change_profile.css" %}">
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <h1> Here you can change information about you </h1>

{#        <div class="content">#}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" >Update profile</button>
            </form>
{#        </div>#}

    </div>
{% endblock content%}

coffehouse/templates/users/creation_service_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Added new service</title>
</head>
<body>
    <h1> New service saw added! </h1>
</body>
</html>

coffehouse/templates/users/login.html
{% extends 'base.html' %}

{% block title %} Login to our system {% endblock %}

{% block extra_head %} 
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/users/login_style.css" %}">
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <h1> Login to our system </h1>

        <div class="login_forms">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="button"> Log in </button>
            </form>
        </div>

    </div>
{% endblock content%}

{% block extra_scripts %}
{#    <script>#}
{#        $("#id_login").change(function () {#}
{#          console.log( $(this).val() );#}
{#        });#}
{#    </script>#}
      <script>
        $("#id_login").change(function () {
          var username = $(this).val();

          $.ajax({
            url: '/ajax/validate_username/',
            data: {
              'username': username
            },
            dataType: 'json',
            success: function (data) {
              if (!data.is_taken) {
                alert("A user with this username is not registered.");
              }
            }
          });
        });
    </script>
{% endblock extra_scripts %}

coffehouse/templates/users/profile.html
{% extends 'base.html' %}

{% block title %} Welcome home {% endblock %}

{% block extra_head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/users/profile_style.css" %}">
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <h1> Profile for, {{ user.username }}! </h1>

        <br> <br> <br>

        <h3>User name</h3>
        <div class="field">
            {{ base_user.username }}
        </div>
        <br>

        <h3>First name</h3>
        <div class="field">
            {{ base_user.first_name }}
        </div>
        <br>

        <h3>Last name</h3>
        <div class="field">
            {{ base_user.last_name }}
        </div>
        <br>

        <h3>E-mail address</h3>
        <div class="field">
            {{ base_user.email }}
        </div>
        <br>

        <h3>Address</h3>
        <div class="field">
            {{ customer.address }}
        </div>
        <br>

        <h3>Country</h3>
        <div class="field">
            {{ customer.country }}
        </div>
        <br> <br>

{#        <button class="change_profile"><a href="{% url 'users:change_profile' %}">Change profile</a></button>#}

    </div>
{% endblock content %}

coffehouse/templates/users/register.html
{% extends 'base.html' %}

{% block title %} Login to our system {% endblock %}

{% block extra_head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/users/register_style.css" %}">
{% endblock extra_head %}

{% block content %}
    <div class="content">
        <h1> Register to our shop! </h1>

        <div class="register_forms">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="button"> Register </button>
            </form>
        </div>
        <p> Already have account? <a href="{% url 'users:login' %}"> LOG IN. </a> </p>
    </div>
{% endblock content%}

coffehouse/templates/users/register_error.html
{% extends 'base.html' %}

{% block title %} Error {% endblock %}

{% block extra_head %}
{#    link here custom .css file#}
{% endblock extra_head %}

{% block content %}

    <div class="content">
        <h1> Unsuccessful login because: </h1>

        {% for error in reasons %}
        <p> {{ error }}</p><br>
    {% endfor %}
    </div>

{% endblock content%}

coffehouse/templates/users/test_register.html
{% extends 'base.html' %}

{% block title %} Register user {% endblock %}

{% block extra_head %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/users/register_style.css" %}">
{% endblock extra_head %}


{#{% block extra_scripts %}#}
{#    <script>#}
{#        $("#id_username").change(function () {#}
{#          console.log( $(this).val() );#}
{#        });#}
{#    </script>#}
{#{% endblock extra_scripts %}#}

{% block content %}
    <h1> Register to our system </h1>

{#    <div class="content">#}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-success">Post</button>
        </form>

        <p> Already have account? <a href="{% url 'users:login' %}"> Log in. </a> </p>
{#    </div>#}

{% endblock content%}

coffehouse/templates/users/welcome_new_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome!</title>
</head>
<body>
    <h1> Welcome at our site! </h1>
    <p>{{ user.username }}</p>
    <p>{{ user.is_customer }}</p>
</body>
</html>